brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# 设置brokerIP1为服务器公网IP
#brokerIP1={{PUBLIC_IP}}
# 允许自动创建Topic
autoCreateTopicEnable=true
# 允许自动创建订阅组
autoCreateSubscriptionGroup=true

# 降低内存相关参数
maxMessageSize=1024
flushCommitLogLeastPages=1
flushConsumeQueueLeastPages=1
